# Copy of https://github.com/KWasm/kwasm-operator/blob/main/examples/kind/cluster.yaml
# With amendments for ingress, see https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
- role: worker
- role: worker