---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyper-server
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
      labels:
        app: hyper-server
    spec:
      runtimeClassName: crun
      nodeSelector:
        kwasm.sh/kwasm-provisioned: kind-worker2
      containers:
      - args:
        - /hyper-server.wasm
        - "3000"
        image: georgenicoll/hyper-server-buildah-kwasm:latest
        name: hyper-server
---
apiVersion: v1
kind: Service
metadata:
  name: hyper-server
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: hyper-server
---