spin_version = "1"
authors = ["George Nicoll"]
description = "hyper-server-spin wasm playaround"
name = "hyper-server-spin"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "spin_rust_hello.wasm"
[component.trigger]
route = "/hello"